### Analizar predicción
POST {{base_url}}/ai/analyze-prediction
    ?unit_price=36.21
    &quantity=100
    &predicted_total=2953.08
    &product_name=Producto%2014
Authorization: Bearer {{token}}

### Analizar predicción 2
POST {{base_url}}/ai/analyze-prediction
    ?unit_price=3000
    &quantity=300
    &predicted_total=90000
    &product_name=Harina
Authorization: Bearer {{token}}

