### Listar customer-segments
GET {{base_url}}/ml/customer-segments
Authorization: Bearer {{token}}


### Listar customer-segments
POST {{base_url}}/ml/predict
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "unit_price": "3000",
  "quantity": "300",
  "company_product_id": "20"
}


### Analizar predicción
POST {{base_url}}/ai/analyze-prediction
    ?unit_price=3000
    &quantity=300
    &predicted_total=39429.54
    &company_product_id=14
Authorization: Bearer {{token}}


### Analizar predicción
POST {{base_url}}/ai/analyze-prediction
    ?unit_price=10
    &quantity=10
    &predicted_total=39429.54
    &company_product_id=19
Authorization: Bearer {{token}}


### Listar customer-segments
POST {{base_url}}/ai/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "¿Qué clientes compran más?",
  "history": []
}

### Follow-up con historial
POST {{base_url}}/ai/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "¿Y cuánto gastaron en total?",
  "history": [
    {
      "role": "user",
      "content": "¿Qué clientes compran más?"
    },
    {
      "role": "assistant",
      "content": "La herramienta me proporcionó la información de los 10 clientes que han realizado más compras en nuestra empresa. Los clientes con más compras son África Nogueira y Celso Ibañez, con 38 y 25 compras respectivamente."
    }
  ]
}

### Chat con RAG
POST {{base_url}}/ai/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "¿Qué clientes compran más?",
  "history": [],
  "session_id": "test-session-1"
}